### ISSUE TITLE
Что будет? Список? Или стартовые коды для него?

### ISSUE THREAD

**Issue by St3p40** [AlexGyver/GyverKIT#1]
Пока пусто

**Comment by kotleni** [comment]
Тот же вопрос, но не решился спросить)

**Comment by AlexGyver** [comment]
Будут библиотеки и какие то другие файлы :) коды будут на сайте, но может и тут продублируем если получится удобная иерархия

**Comment by kotleni** [comment]
Библиотеки для работы с модулями в наборе?

**Comment by AlexGyver** [comment]
Ну, логично. Просто все в одном месте, не собирать же их по всему интернету ссылками

**Comment by kotleni** [comment]
**Удобно, но что насчет актуальных версий?**

**Comment by AlexGyver** [comment]
Каких?

**Comment by kotleni** [comment]
Библиотек

**Comment by AlexGyver** [comment]
Некоторые библиотеки для модулей не обновлялись уже сто лет и обновляться не будут

**Comment by kotleni** [comment]
Понял, спасибо.

**Comment by St3p40** [comment]
> Некоторые библиотеки для модулей не обновлялись уже сто лет и обновляться не будут

А может правки?

**Comment by AlexGyver** [comment]
> А может правки?
>
Если будут исправляться какие-то критические ошибки, либы будут обновлены

**Comment by St3p40** [comment]
Ладно, вижу уже есть много чего. Закрываю issue.
